create table if not exists heroes (
    id integer primary key autoincrement,
    name string not null,
    primary_attr string not null,
    roles string not null,
    lore string,
    str string,
    agi string,
    int string,
    str_growth string,
    agi_growth string,
    int_growth string,
    hp string,
    mana string,
    hp_regen string,
    mana_regen string,
    damage string,
    bat string,
    move_speed string,
    day_vision string,
    night_vision string,
    attack_range string,
    turn_rate string,
    missile_speed string
);
